### ISSUE TITLE
Unable to change mode with TAP_1

### ISSUE THREAD

**Issue by undeterred965** [eouia/MMM-Touch#1]
I have a very simple config.js in MagicMirror setup for testing purposes where the MMM-Touch module will not change modes correctly. The config.js contains:

                {
                        module: "MMM-Touch",
                        position: "top_right",
                        config: {
                                debug: true,
                                useDisplay: true,
                                defaultMode: "main",
                                gestureCommands: {
                                        "main": {
                                                        "TAP_1": (commander) => {
                                                                commander.setMode("currentweather")}
                                                },
                                        "currentweather": {
                                                        "TAP_1": (commander) => {
                                                                commander.setMode("main")}
                                                }
                                }
                        }
                },

Upon tapping the touchscreen (a HyperPixel4 from pimoroni.com) the following error is displayed in the console:

Uncaught TypeError: Cannot set property 'innerHTML' of null      :8080/modules/.../MMM-Touch.js:213

**Comment by undeterred965** [comment]
![image](https://user-images.githubusercontent.com/62571573/77365397-f8111580-6d4d-11ea-9f35-36b33f361408.png)

**Comment by eouia** [comment]
I’ll expect morning. Is there another issue? Without mode, does it work?

**Comment by undeterred965** [comment]
There is a separate issue which I've tried to ignore in my project. That is PRESS_1 is not recognised at all.
I haven't noted anything else.

**Comment by eouia** [comment]
Had a bug. fixed. 
However for PRESS event, have no idea. What does log say in front-end console when you try PRESS?

**Comment by undeterred965** [comment]
TAP_1 works, thanks. The PRESS_1 still doesn't. This is the log when I try a PRESS_1 using your default configuration:

![Error2](https://user-images.githubusercontent.com/62571573/77419551-88883e00-6dc0-11ea-81cc-4af95680f800.PNG)

**Comment by undeterred965** [comment]
Ahh, I spoke too soon. TAP_1 only works with useDisplay: true
I have a simple config.js again consisting of:

```
module: "MMM-Touch",
position: "top_right",
config: {
        debug: true,
        useDisplay: false,
        defaultMode: "default",
        gestureCommands: {
                "default": {
                        "TAP_1": (commander) => {
                                commander.sendNotification("SHOW_ALERT", {
                                        title: "TOUCH Test.",timer: 3000})},
                        "SLIDE_DOWN_1": (commander) => {
                                commander.shellExec("sudo reboot now")},
                        "SLIDE_DOWN_2": (commander) => {
                                commander.shellExec("sudo shutdown -h now")}
                }
        }
}

```
![Error3](https://user-images.githubusercontent.com/62571573/77439675-3f93b200-6ddf-11ea-9a2a-e5881a43d211.PNG)

**Comment by eouia** [comment]
Sorry for the inconvenience.
1) I made a mistake on code so fixed for useDisplay
2) For PRESS,
  - in some environments, contextMenu could prevent proper event firing, so fixed.
  - And unnecessary assertion is removed. I think this was the reason of your issue. try it again.

**Comment by undeterred965** [comment]
Not at all, I'm glad that it can be debugged so my mini-MM will work.

TAP_1 and PRESS_1 now work for useDisplay: false
Unfortunately SLIDE_DOWN_2 is not executing my shutdown command. My config.js is again simple:

```
                        module: "MMM-Touch",
                        position: "top_right",
                        config: {
                                debug: true,
                                useDisplay: false,
                                defaultMode: "default",
                                gestureCommands: {
                                        "default": {
                                                "TAP_1": (commander) => {
                                                        commander.sendNotification("SHOW_ALERT", {
                                                        title: "TOUCH Test.",timer: 3000})},
                                                "PRESS_1": (commander) => {
                                                        commander.shellExec("sudo reboot now")},
                                                "SLIDE_DOWN_2": (commander) => {
                                                        commander.shellExec("sudo shutdown -h now")}
                                                }
                                }
                        }
```

No error message this time. The SLIDE_DOWN_2 is recognised, just the command is not executed:

![Error4](https://user-images.githubusercontent.com/62571573/77453168-ca2fdd80-6dee-11ea-9cb0-e0834d30dc36.PNG)

**Comment by eouia** [comment]
There is no SLIDE Gesture. Only MOVE and SWIPE by speed.

**Comment by undeterred965** [comment]
My bad.
It works perfectly now, thanks.
Who closes the issue?
